version: 2.1
orbs:
  docker: circleci/docker@1.5.0

# Modified Accuratiorem's YML file

jobs:
  provectus_job:
    environment:
      IMAGE: aprokopyev/provectus
    executor: docker/docker # default python executor
    steps:
      - setup_remote_docker
      - checkout
      - docker/check # verify dockerhub login
      - run:
          name: build step
          working_directory: "devops/02\ -\ dockerfile"
          command: |
            SHORT_COMMIT_ID=$(git rev-parse --short "${CIRCLE_SHA1}")
            IMAGE_TAG="0.$CIRCLE_BUILD_NUM-$SHORT_COMMIT_ID"
            IMAGE_NAME="$IMAGE:$IMAGE_TAG"
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME
workflows:
  on_commit:
    jobs:
      - provectus_job:
          context:
            - Context1
          filters:
            branches:
              only: main
