version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  build-and-push:
    environment:
      IMAGE: aprokopyev/flaskapp
      docker login b742caaa-cdb1-49d3-a99b-a11b1506de7b
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: BUILD
          working_directory: "devops/02\ -\ dockerfile"
          command: |
            SHORT_COMMIT_ID=$(git rev-parse --short "${CIRCLE_SHA1}")
            IMAGE_TAG="0.$CIRCLE_BUILD_NUM-$SHORT_COMMIT_ID"
            docker build -t $IMAGE:$IMAGE_TAG .
            docker push $IMAGE:$IMAGE_TAG

workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - docker-hub-creds
          filters:
            branches:
              only: main






## Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
## Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
#  welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run
